name: Publish

on:
  push:
    tags:
      - 'v**'

jobs:
  tests:
    uses: ./.github/workflows/tests.yml


  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - run: pip install -r script/release/requirements.txt

      - run: script/release/build

      - uses: actions/upload-artifact@v4
        with:
          name: dist
          path: dist


  publish:
    runs-on: ubuntu-latest

    needs:
      - tests
      - build

    environment: release
    permissions:
      id-token: write

    steps:
      - uses: actions/download-artifact@v4
        with:
          name: dist
          path: dist

      - name: Display structure of downloaded files
        run: ls -R

      - name: Publish package distributions to TestPyPI
        uses: pypa/gh-action-pypi-publish@release/v1
