name: Publish

on:
  push:
    tags:
      - 'v*'

jobs:
  tests:
    uses: ./.github/workflows/tests.yml

  publish:
    runs-on: ubuntu-latest
    needs:
      - tests

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'

    - run: pip install -r script/release/requirements.txt

    - run: script/release/release
      env:
        TWINE_USERNAME: __token__
        TWINE_PASSWORD: ${{ secrets.PYPI_TOKEN }}
        TWINE_REPOSITORY_URL: https://test.pypi.org/legacy/
