name: Tests

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  tests:
    strategy:
      matrix:
        python-version: ['3.8', '3.9', '3.10', '3.11', '3.12']
        test-os: [ubuntu-latest, windows-latest]

    runs-on: ${{ matrix.test-os }}
    defaults:
      run:
        shell: bash

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          allow-prereleases: true

      - name: Install Dependencies
        run: |
          pip install --upgrade pip
          pip install tox tox-gh-actions

      - name: Test with tox
        run: tox
